--| column     |      type      |
--|------------|----------------|
--| id         | auto_increment |
--| first_name | varchar(50)    |
--| last_name  | varchar(50)    |
--| job        | varchar(50)    |
--| country    | varchar(50)    |
--| age        | Int            |