insert into users (first_name, last_name, job, country, age) values ('Samuel', 'Martinez', 'Web Developer II', 'Thailand', 67);
insert into users (first_name, last_name, job, country, age) values ('Timothy', 'Richards', null, 'Thailand', 37);
insert into users (first_name, last_name, job, country, age) values ('Beverly', 'Wallace', null, 'Namibia', 40);
insert into users (first_name, last_name, job, country, age) values ('Willie', 'Hayes', null, 'Philippines', 35);
insert into users (first_name, last_name, job, country, age) values ('Denise', 'Gibson', 'VP Marketing', 'Indonesia', 45);
insert into users (first_name, last_name, job, country, age) values ('Ashley', 'Simpson', 'Software Consultant', 'Iran', 60);
insert into users (first_name, last_name, job, country, age) values ('Jose', 'Green', 'Quality Control Specialist', 'Portugal', 55);
insert into users (first_name, last_name, job, country, age) values ('Melissa', 'Ramos', 'Human Resources Assistant I', 'Colombia', 60);
insert into users (first_name, last_name, job, country, age) values ('Jesse', 'Morris', null, 'Indonesia', 69);
insert into users (first_name, last_name, job, country, age) values ('Mildred', 'Jones', 'Financial Analyst', 'Philippines', 79);
insert into users (first_name, last_name, job, country, age) values ('Frances', 'Armstrong', null, 'Philippines', 44);
insert into users (first_name, last_name, job, country, age) values ('Irene', 'Peters', 'Information Systems Manager', 'United States', 12);
insert into users (first_name, last_name, job, country, age) values ('Matthew', 'Lane', null, 'Serbia', 68);
insert into users (first_name, last_name, job, country, age) values ('Kathryn', 'Ellis', null, 'Indonesia', 17);
insert into users (first_name, last_name, job, country, age) values ('Roy', 'Little', 'Administrative Officer', 'Philippines', 43);
insert into users (first_name, last_name, job, country, age) values ('Alan', 'Parker', 'Account Representative IV', 'Yemen', 74);
insert into users (first_name, last_name, job, country, age) values ('Ruby', 'Gordon', 'Accounting Assistant I', 'China', 57);
insert into users (first_name, last_name, job, country, age) values ('Betty', 'Nelson', null, 'Brazil', 13);
insert into users (first_name, last_name, job, country, age) values ('Victor', 'Reyes', 'Help Desk Operator', 'Indonesia', 44);
insert into users (first_name, last_name, job, country, age) values ('Bobby', 'Oliver', null, 'Sweden', 17);